- World/Updates/Rel20/20000_02_Tutenkash_Gong_scripted.sql
This fix will make the gong in RFD spawn the waves of creatures,
culminating in the spawning of Tuten'kash (boss)
> Tuken'kash's gong (RFD)

- World/Updates/Rel20/20000_03_Guardian_of_Blizzard_non_combat_fix.sql
Record was not set up to use scripts (missing EventAI)
Faction ID changed to Demon (73)
> Guardian of Blizzard no combat fix

- World/Updates/Rel20/20000_07_Missing_Developer_Items_Added.sql
Martin Fury (17)
Martins Broken Staff (192)
> Missing developer items added

- World/Updates/Rel20/20000_02_Tutenkash_Gong_scripted.sql
- World/Updates/Rel20/20000_04_Felwood_Corrupted_Plant_fix.sql
- World/Updates/Rel20/20000_06_DbDocs_update.sql
- World/Updates/Rel20/20000_07_Missing_Developer_Items_Added.sql
Corrections made to World Update scripts
> Corrections made to World Update scripts

- World/Updates/Rel20/20000_18_Start_Up_Fixes.sql
This takes the errors down to 0, at this point in time.
> Start-up Error Fixes

- World/Updates/Rel20/20000_18_Start_Up_Fixes.sql
- World/Updates/Rel20/20000_19_Synching_of_EventAI_Action_Types.sql
1) Took a disliking to dashes
2) Reference name too long
> Corerections made to updates

- World/Updates/Rel20/20000_20_Quest_Hunting_for_Ectoplasm_fix.sql
The makes the Ectoplasmic Distiller work as it should do, and requires
the version of the core at this point is time, due to the addition an
use of a new condition: CONDITION_GAMEOBJECT_IN_RANGE
> Quest: Hunting for Ectoplasm fix

- World/Updates/Rel20/20000_23_Blades_Edge_Ogre_Brew.sql
Potions can only be used in Blades Edge mountains
> Ogre Brew in Blades Edge mountains

- World/Updates/Rel20/20000_24_Quest_Hypercapacitor_Gizmo.sql
Quest Hypercapacitor Gizmo
dbscripts_on_go_use entries added in order to make the quest work.
Taken from Zero
> Fix by Evildead - Hypercapacitor Gizmo

- World/Updates/Rel20/20000_24_Quest_Hypercapacitor_Gizmo.sql
Only needs change to UnitFlags, plus altering scale resulted in the
creature being too large.
> Script altered

- World/Updates/Rel20/20000_25_Tortured_skeleton_issue_fix.sql
Tortured Skeleton in Shadow Labyrinth not standing when aggro'd fix
> Fix by SylvainNeau - Tortured Skeleton

- World/Updates/Rel20/20000_26_Fel_Stalker_issue_fix.sql
Fel Stalker shouldn't be controlled by demonists
> Fix by SylvainNeau - Fel Stalker

- World/Updates/Rel20/20000_27_Terl_Arakor_Wetlands_gossip_text.sql
This NPC will now have a choice of things to say when interacted with.
> Terl Arakor - missing gossip text added

- World/Updates/Rel21/21000_08_quest_wolves_across_the_border.sql
Quest 'Wolves Across The Border' should only be available once the quest
'Eagan Peltskinner' has been handed in.
> Quest Wolves Across The Border fix

- World/Updates/Rel21/21000_09_quest_9447_incorrect_speech.sql
> Quest 9447 Incorrect Speech

- World/Updates/Rel21/Rel21_2_2_Windrunner_Spire_NPCs.sql
Corrections made to the location and movement of the NPCs in Windrunner
Spire (Ghostlands)
> Windrunner Spire NPC corrections (fix by necrovoice)

- World/Updates/Rel21/Rel21_2_4_Crust_Busters.sql
Crust Busters in Outlands have an incorrect UnitFlags setting
> Crust Busters in Helfire

- World/Updates/Rel21/Rel21_2_2_Windrunner_Spire_NPCs.sql
- World/Updates/Rel21/Rel21_2_3_Zaxxis_NPCs.sql
- World/Updates/Rel21/Rel21_2_4_Crust_Busters.sql
There were too many characters in the @cNewDescription
> Corrections made to scripts

- World/Updates/Rel21/Rel21_2_7_start_up_error_fixes.sql
> Start up error fixes

- World/Updates/Rel21/Rel21_2_7_start_up_error_fixes.sql
> Correction made to script (database name deleted)

- World/Updates/Rel21/Rel21_2_8_burster_worms.sql
- World/Updates/Rel21/Rel21_2_9_npc_shaheen.sql
Burster Worms and NPC Shaheen scripts added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/39)
> Burster Worms and NPC Shaheen scripts added

- World/Updates/Rel21/Rel21_2_10_Quest_27469.sql
Quest 27469 Friends on The Other Side
Implemented for Horde and Alliance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/40)
> Quest 27469 Friends on The Other Side

- World/Updates/Rel21/Rel21_2_11_Ghostlands Guardian_waypoints.sql
- World/Updates/Rel21/Rel21_2_12_Remove_imp_spell_from_trainers.sql
- World/Updates/Rel21/Rel21_2_13_Foodbar Fix.sql
- World/Updates/Rel21/Rel21_2_14_portal_for_quest_continuation.sql
- World/Updates/Rel21/Rel21_2_15_warlock_pet_mana_fix.sql
- World/Updates/Rel21/Rel21_2_16_Hellfire_portals.sql
Added wapoints to Ghostlands guardian
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/42)
> Guardian waypoints added

- World/Updates/Rel21/Rel21_2_16_Hellfire_portals.sql
Added short and long descriptions to update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/44)
> Added short and long descriptions to update

- World/Updates/Rel21/Rel21_2_17_BRD_updates.sql
Cmangos BRD Grimm Guzzler updates
> Cmangos BRD Grimm Guzzler updates

- World/Updates/Rel21/Rel20_to_BaseRel21_Updates/Rel21_2_12_Remove_imp_spell_from_trainers.sql
- World/Updates/Rel21/Rel20_to_BaseRel21_Updates/Rel21_2_13_Foodbar Fix.sql
- World/Updates/Rel21/Rel20_to_BaseRel21_Updates/Rel21_2_14_portal_for_quest_continuation.sql
- World/Updates/Rel21/Rel20_to_BaseRel21_Updates/Rel21_2_15_warlock_pet_mana_fix.sql
- World/Updates/Rel21/Rel20_to_BaseRel21_Updates/Rel21_2_19_Outland_first_aid.sql
- World/Updates/Rel21/Rel20_to_BaseRel21_Updates/Rel21_2_20_hillsbrad_foothills_quest_fixes.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/47)
> Update and corrections

- World/Updates/Rel21/Rel21_02_23_start_up_error_fixes.sql
- World/Updates/Rel21/Rel21_02_24_Troublesome_Distractions_fix.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/49)
> Quest and start up fixes

- World/Updates/Rel21/Rel21_02_23_start_up_error_fixes.sql
- World/Updates/Rel21/Rel21_02_24_Troublesome_Distractions_fix.sql
- World/Updates/Rel21/Rel21_02_25_silvermoon_city_fix_pt1.sql
- World/Updates/Rel21/Rel21_02_26_Start_up_error_fix.sql
- World/Updates/Rel21/Rel21_02_27_Tukemuth_waypoints.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/50)
> Startup errors and silvermoon update part1

- World/Updates/Rel21/Rel21_02_25_silvermoon_city_fix_pt1.sql
- World/Updates/Rel21/Rel21_02_29_Update_Sunwell_Pleateau.sql
- World/Updates/Rel21/Rel_21_02_28_silvermoon_city_fix_pt2.sql
The first push of part 1 was cut off mid code and needed to be updated to correct errors caused. Part 2 is a continuation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/52)
> Corrections and additions

- World/Updates/Rel21/Rel21_02_30_Expedition_Outrider_update.sql
- World/Updates/Rel21/Rel21_02_31_Waypoints_for_2802_and_5747.sql
- World/Updates/Rel21/Rel21_02_32_Ironforge_Guard.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/54)
> Develop21 (UDB updates)

- World/Updates/Rel21/Rel21_02_22_quest_12687.sql
- World/Updates/Rel21/Rel21_02_36_Jane_Nova_Jessel.sql
- World/Updates/Rel21/Rel21_02_37_Quest_12680_Grand_Theft_Palomino.sql
- World/Updates/Rel21/Rel21_02_38_Cat_Ambassador_Bloodelf_OHMY.sql
- World/Updates/Rel21/Rel21_02_39_Scorchshell_Pincer.sql
- World/Updates/Rel21/Rel21_02_40_Eye_of_Acherus.sql
- World/Updates/Rel21/Rel21_02_41_quests_411_and_808_-_updates.sql
- World/Updates/Rel21/Rel21_02_42_quest_12687.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/56)
> Various Fixes and updates

- World/Updates/Rel21/Rel21_02_46_more gossip.sql
- World/Updates/Rel21/Rel21_02_47_Silvermoon Bazzar event.sql
- World/Updates/Rel21/Rel21_02_48_Silvermoon ranger.sql
- World/Updates/Rel21/Rel21_02_49_Silvermoon_city_fix_pt3.sql
- World/Updates/Rel21/Rel21_02_50_Silvermoon_NPC_-_Bithrus.sql
- World/Updates/Rel21/Rel21_02_51_Conjurer_Tyren.sql
- World/Updates/Rel21/Rel21_02_52_Tiny_Arcane_Construct_and_Trayanise.sql
Pulled from UDB repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/58)
> More Silvermoon

- World/Updates/Rel21/Rel21_02_53_More_updates_fixes_and_corrections..sql
- Twinkle, added kneeling emote
- Sangrias Stillblade now uses the correct equipment
- Torch can be used to get out from Scholomance
- Gormok the Impaler
- Fixed Z position of GO 30856
- Marshal Dughan - gossip added
- missing text
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/59)
> Updates, Fixes and corrections

- World/Updates/Rel21/Rel21_02_62_Demon_Trainer_Update.sql
- World/Updates/Rel21/Rel21_02_63_Pink_Elekk.sql
- World/Updates/Rel21/Rel21_02_64_Love_is_in_the_air.sql
- World/Updates/Rel21/Rel21_02_65_Lakeshire_-_kids.sql
- World/Updates/Rel21/Rel21_02_66_Blood_Elves_at_sunstrider_isle.sql
- World/Updates/Rel21/Rel21_02_67_Updates_and_improvements_to_NPCs.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/63)
> Various Updates

- World/Updates/Rel21/Rel21_02_68_Woo_Ping_Gossip.sql
Woo Ping of Stormwind will now correctly point you to Buliwyf the dwarf
in Ironforge to train in guns wapon skill.
** NOTE please delete the Client Cache folder to account for this
uodate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/64)
> Woo Ping Gossip Update

- World/Updates/Rel21/Rel21_02_69_Cabal_Ritualist.sql
- World/Updates/Rel21/Rel21_02_70_ q.9305 Spare Parts.sql
- World/Updates/Rel21/Rel21_02_71_Missing_Sand_Shark_pluss_WP.sql
- World/Updates/Rel21/Rel21_02_72_Ironforge_Guard_1894_WP.sql
- UDB [183] Cabal Ritualist
-- Cabal Ritualist (groups should be linked)
-- UDB https://github.com/unified-db/Database/commit/4e9a2b3
- UDB -q.9305 'Spare Parts' https://github.com/unified-db/Database/commit/75860f6
-- q.9305 'Spare Parts'
-- gameobject will despawn after item collected.
-[072] ClassicDB Backoprt#2 Part1. (Modified) https://github.com/unified-db/Database/commit/7907896
-- Added Sand shark NPC and waypoints
-[073] ClassicDB Backport#2 Part2. (Partial) https://github.com/unified-db/Database/commit/aa496f8
-- Ironforge Guard #1894
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/65)
> Updates from UDB

- World/Updates/Rel21/Rel21_02_83_Quest_27469_rollback.sql
This quest was added in patch 4.0.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/68)
> Removed quest 27469

- World/Updates/Rel21/Rel21_02_28_silvermoon_city_fix_pt2.sql
Also corrected case to be consistent with the rest of the file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/69)
> Added missing semicolon at end of update statment

- World/Updates/Rel21/Rel21_02_91_Object_181011_hight_fix.sql
- World/Updates/Rel21/Rel21_02_92_quest_11174.sql
- World/Updates/Rel21/Rel21_02_93_Fix_creature_10076_ Faction.sql
Magister Duskwithers Journal is now correctly place on the table and not
on the floor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/72)
> Game object Height Fix

- World/Updates/Rel21/Rel21_02_94_batch_item_object_update.sql
- rename Item 46767 to correct name
Credit for the below fix go to UDB
- UDB [540] Item: 'Crown Chemical Co. Supplies'
- UDB [297] Flags for few items...
- UDB [369] Milly's Harvest / Update for [369]
UDB [371] Altar of the Deeps + Script updated for Morridune
UDB [519] Fix Grim Batol sign position in Wetlands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/73)
> Batch update for items and objects

- World/Updates/Rel21/Rel21_03_02_blackpaw_shaman.sql
- World/Updates/Rel21/Rel21_03_2_blackpaw_shaman.sql
Added mana to Blackpaw Shaman. They now cast spells.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/76)
> Blackpaw Shaman mana update

- World/Updates/Rel21/Rel21_03_03_Milton_Beats_faction.sql
Milton Beats will now attack players who summon him.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/77)
> Milton Beats faction update

- World/Updates/Rel21/Rel21_03_04_gobject83_position_update.sql
The sign in Westfall that points to Jangolode mines no longer defies the
laws of physics.
- Thanks to Pyotr for pointing out the issue in the tracker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/78)
> Game object #83 updated

- World/Updates/Rel21/Rel21_03_18_Code_corrections.sql
A few of the previous updates had some flaws in the sql and caused core
startup errors. this should correct that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/80)
> Code corrections

- World/Updates/Rel21/Rel21_03_020_Dragonblight_NPC_updates.sql
- World/Updates/Rel21/Rel21_03_021_Deep_Elem_Sign.sql
- World/Updates/Rel21/Rel21_03_022_Fel_cannon_movement.sql
-Remove duplicate spawn location for a GO
-Focus Wizard and Dragonblight Mage Hunter should no longer fly
-The image of Grand Magus Telestra Should not wander about.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/82)
> Dragonblight  updates

- World/Updates/Rel21/Rel21_03_024_Quest_11715_and_10506.sql
The following quests will now correctly fulfill the quest requirements
-- Fueling the Project quest update (Quest:11715)
-- A Dire Situation quest update (Quest: 10506 )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/84)
> Quest 11715 and 10506 updates

- World/Updates/Rel21/Rel21_03_027_Quest_10427_Fix.sql
Creatures of the Eco-Domes quest can now be completed.
**NOTE** There is still a minor issue where thePC will remain in a
combat state until out of range.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/86)
> Quest_10427_Fix

- World/Updates/Rel21/Rel21_03_028_Dragonblight_Updates.sql
- Magister Keldonus and Grand Magus Telestra argo conversations
- Captain Emmy Malin
- Goramosh say on argo
- Captain Shely
- Lieutenant Ta'zinni
- Delete duplicate Object
- The Focus on the Beach Quest update
- Atop the Woodlands Quest update
- The End of the Line Quest update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/87)
> Dragonblight improvements

- World/Updates/Rel21/Rel21_03_030_Wind_Trader_Marid_Support.sql
Added script and other enhancements to Wind Trader Marid so the NPC now
supports the quest
Troublesome Distractions (#10273)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/88)
> Wind Trader Marid Quest Support

- World/Updates/Rel21/Rel21_03_031_q.11008_Fires_Over_Skettis.sql
Added missing Game Objects: 185549
Added missing kill credit markers: 22991
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/89)
> Fires Over Skettis Update

- World/Updates/Rel21/Rel21_03_032_Morbent_Fel_Script.sql
This script will complete the non working Quest: Morbent Fel
Partial script credit:
https://github.com/ACID-Scripts/TBC/commit/bc2a3f7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/90)
> NPC Morbent Fel scripts

- World/Updates/Rel21/Rel21_03_036_Quest_Teleport_This.sql
- World/Updates/Rel21/Rel21_03_037_NPC_15006_gossip_menu.sql
The quest Teleport this! now functions as intended.
- Added Correct Spells to controlled NPCs
- Added NPC script for quest completion
- Added Target Game objects support for spell 38920
---------------------
-- Deze Snowbane gossip updated for proper battle grounds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/92)
> Quest. Teleport This! support

- World/Updates/Rel21/Rel21_03_038_Deep_Elem_Sign_Update_2.sql
- World/Updates/Rel21/Rel21_04_003_Deep_Elem_Sign_Update_2.sql
The previous update correct the sign from floating in the air.. this
moves it to the correct place ont eh ground.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/93)
> Deep Elm Sign update #2

- World/Updates/Rel21/Rel21_04_004_Quest_11979.sql
Quest 11979 "The Taunka and the Tauren" is supposed to be alternate
starting point for quest 11978 "Into the Fold" for players, who come
from the east. Players who come from the west get quest 11977 "A Tauren
Among Taunka".
-- Credit https://github.com/unified-db/Database/commit/297f4d0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/94)
> The Taunka chain corrected

- Rel21_04_005_Tandrine_Gossip.sql
- Rel21_04_006_Update_NPC_Succubus.sql
Tandrine, gossip added
Camberon, Movetype updated
NPC controlled Succubus Minion ExtraFlas updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/95)
> Updated NPCs Tandrine and Camberon

- World/Updates/Rel21/Rel21_06_002_q.11676__Merciful_Freedom.sql
- World/Updates/Rel21/Rel21_06_003_NPC_Lanti'gah_updates.sql
--UDB
[240] q.11676 'Merciful Freedom'
- quest fixed
- Scourge Prisoner spawn sync with cage
https://github.com/unified-db/Database/commit/7c35d47#diff-4d9f10b324d7920eae0cc823ee441c07
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/97)
----------
--UDB Update
[213] Lanti'gah
Lanti'gah - Barrens
Spawnpoint and movement corected
unified-db/Database@4096977
> q.11676_ Merciful_Freedom

- World/Updates/Rel21/Rel21_06_004_Lunar_Firework_credit_marker.sql
- World/Updates/Rel21/Rel21_06_005_Verog_increase_spawn_chance.sql
Updates from NostraliaWow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/98)
> Updates from NostraliaWow

- World/Updates/Rel21/Rel21_06_006_q.11876_scripting.sql
quest fixed:
- Trapped Mammoth Calf will look trapped ... not only standing on trap
- missing ones added
- Trapped Mammoth Calf sync with traps
- Mammoth trap - will go back to default state without server restart
thx to @Tauriella for report
https://github.com/unified-db/Database/commit/9d1805b
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/99)
> q.11876 'Help Those That Cannot Help Themselves

- InstallDatabases.bat
- Tools/mangosCreateUser.sql
Updated InstallDatabases.bat with mangos user creation and privileges granting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/96)
> Added mangos user creation to InstallDatabases.bat

- World/Updates/Rel21/Rel21_06_007_q.10438_On_Nethery_Wings.sql
Set z axis a little higher
Adjusted HP on npc to allow for faster killing( this is kind of a hack
fix to prevent the continues dropping out of combat)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/100)
> q.10438 On Nethery Wings

- World/Updates/Rel21/Rel21_06_0012_Dalaran_Books.sql
- World/Updates/Rel21/Rel21_06_011_Dalaran_Fountain.sql
- World/Updates/Rel21/Rel21_06_012_Dalaran_Books.sql
Dalaran Fountain adjusted to be upright
------------------------
The books around Dalaran can be read and will despawn after about a 98
seconds.
(Need a better way to read/desapawn when the books are closed by the
player) changed from default value data5 / data3 = 0/0 respectively
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/102)
> Dalaran updates

- World/Updates/Rel21/Rel21_06_013_Fix_gobject.192824_flags.sql
This object has been changed back. It was added to a previous update and should not have been.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/103)
> object 192824 update

- World/Updates/Rel21/Rel21_06_013_Fix_gobject.192824_flags.sql
Added correct object that should of been in re21_06_012
updated the object that should not of been added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/104)
> Update to previous commit

- World/Updates/Rel21/Rel21_06_014_q.9544_The_Prophecy_of_Akida.sql
... quest scripted
- start script added
- Stillpine Captives will run after cage open. (each has diff wps)
- cages will reset after 5 mins (synch. with Stillpine Captives)
Credit @Grz3s
Also -  fix for [336] q. 9542 - script corrected
thx to @NeatElves
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/105)
> q.9544 'The Prophecy of Akida'

- World/Updates/Rel21/Rel21_06_015_Spirit_Healer.sql
- World/Updates/Rel21/Rel21_06_016_Foreman_Mortuus.sql
Spirit Healers added
Formen Mortuus waypoints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/106)
> Northrend NPC updates

- World/Updates/Rel21/Rel21_06_017_Watch_Commander_Zalaphil.sql
[194] Watch Commander Zalaphil
Watch Commander Zalaphil - equipment
thx to Killyana
source:
https://github.com/unified-db/Database/commit/9078802
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/107)
> Watch Commander Zalaphil

- World/Updates/Rel21/Rel21_06_018_Undercity_Lift_Pt2.sql
This fixes the last lift in undercity for M2 so that it is at the
correct rotation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/108)
> Undercity Lift Part2

- World/Updates/Rel21/Rel21_06_024_quest_9667_with_script.sql
- Princess Stillpine - run added, respawn sync. with object
- High Chief Bristlelimb - flags corrected, equip added
Source: https://github.com/unified-db/Database/commit/d694e8f
- High Chief Bristlelimb - Missed in Rel21_06_019
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/110)
> q.9667 'Saving Princess Stillpine' + Script -- UPDATE

- World/Updates/Rel21/Rel21_06_025_Training_dummy_update.sql
- World/Updates/Rel21/Rel21_06_026_game_object_2846.sql
- Update Training Dummies found around the world.
- Tattered Chest gameobject has been reworked. pools added new and old spawns worked, loot drop updated.
This closes the M2 tracker topic
'loot in chests azuremyst and bloodmyst isle' reported by gambit2312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/112)
> Training dummy update

- Rel21_06_027_q.9663_The_Kessel_Run.sql
Q redone:
- *temp* gossip_options removed
- Now players will get correct credit .. by only clicking at npc.
- conditions corrected
- End script added (player wont keep Elekk anymore after completing
quest)
Source: https://github.com/unified-db/Database/commit/35e0d83
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/113)
> q.9663 'The Kessel Run'

- World/Updates/Rel21/Rel21_06_028_add_missing_NPC.sql
- World/Updates/Rel21/Rel21_06_029_Class_trainers.sql
- Added missing NPC Kieupid
- Updates to NPC gossip menus to proper and updated text for Wrath.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/115)
> Class Trainers update.

- World/Updates/Rel21/Rel21_06_030_NPC_Inhabit_Types.sql
- World/Updates/Rel21/Rel21_06_031_Help_tavara_q9586.sql
- World/Updates/Rel21/Rel21_06_032_Silvermyst_Isle_correction.sql
Source: https://github.com/TBC-DB/Database/commit/8760468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/116)
> Verious Updates

- World/Updates/Rel21/Rel21_06_046_q9514_Rune_Covered_Tablet.sql
- World/Updates/Rel21/Rel21_06_047_q9294_Healing_the_Lake.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/119)
> Various Quest updates

- World/Updates/Rel21/Rel21_06_048_q_9531_Trees_Company_Rework.sql
**# Requires:**
https://github.com/mangos/ScriptDev3/pull/67/commits/e8a39a3199f739537812853198377f5fb3df9b79
- summons corrected
Source: https://github.com/unified-db/Database/commit/ff7b0e8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/120)
> q.9531 'Tree's Company' Rescripted

- World/Updates/Rel21/Rel21_06_053_remove_dbscripts_on_tables.sql
@billy1arm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/122)
> [FIX] Remove obsolete tables if they exist

- World/Updates/Rel21/Rel21_06_054_Gizrul_the_Slavene.sql
- World/Updates/Rel21/Rel21_06_055_NPC_9568_SD3_support.sql
- Updates NPC's scripted spawn location
- Add a Waypont to the creature
for correct movement
- NPC_9568 SD3 support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/123)
> Gizrul the Slavene update

- World/Updates/Rel21/Rel21_06_058_Bijous_quest_faction.sql
-- Thanks to iltuocapo on getmangos.eu for the fix
-- Horde and Alliance
will now get correct quests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/124)
> Bijous Quest RequiredRaces update

- World/Updates/Rel21/Rel21_06_059_Stormwind_Sign_gobject.sql
Removed duplicate sign gobject in stormwind
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/125)
> Removed duplicate sign gobject in stormwind

- World/Updates/Rel21/Rel21_06_060_npc_3301_full_script.sql
At the end of quest 231, NPC 3301 is now fully scripted.
- Port from M0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/126)
> npc 3301 full script

- World/Updates/Rel21/Rel21_06_061_Arcane_Guardian.sql
Source: https://github.com/unified-db/Database/commit/32fb3b0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/127)
> Arcane Guardian waypoints+ Script

- World/Updates/Rel21/Rel21_06_063_NPC_21723_and_23219_rework.sql
-Removed duplicate NPCs
-Added NPCs to a more correct spawn location
- Added missing waypoints
- Removed old guid from required tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/128)
> Blackwind Sabercats, Warp Chasers update. OH MY!

- World/Updates/Rel21/Rel21_06_065_verious_Port_updates.sql
- https://github.com/mangoszero/database/commit/55240d888747c08cd4a2eafa65734126ff98300f
- https://github.com/mangosone/database/commit/c2a040790861010308dd50ebc70e8e7fb6a2d9c8
- https://github.com/mangosone/database/commit/c2a040790861010308dd50ebc70e8e7fb6a2d9c8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/129)
> Ports from M1 and M0

- World/Updates/Rel21/Rel21_06_067_Greater_Spiderweb_spiders.sql
Adds missing Greater Spiders in Ghostlands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/131)
> Add Missing NPC

- World/Updates/Rel21/Rel21_06_069_NPC_Updated_and_Additions.sql
- Add missing Silvermoon Dragonhawks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/133)
> Silvermoon DragonHawk additions

- World/Updates/Rel21/Rel21_06_070_M0_Ports.sql
Credit @bdebaere
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/134)
> Ports from Mangos Zero

- World/Updates/Rel21/Rel21_06_072_Spell_cast_on_quest.sql
The spell The Captain's Kiss shoul;d be cast upon accepting the
following quests
- The Bloodcursed Naga
- The Hopeless Ones...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/135)
> Spell cast on quest accept

- World/Updates/Rel21/Rel21_06_073_Lazy_peon_script_text.sql
Update lazy peon to correct text
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/136)
> Lazy Peon script text

- World/Updates/Rel21/Rel21_06_074_Kessel_run_cleanup.sql
Clean up out of date gossip for the NPCs involved in the Kessel run
quest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/137)
> Kessel run gossip update

- World/Updates/Rel21/Rel21_06_075_Blasted_lands_Portal.sql
Add missing Blasted Land portal in Undercity, Silvermoon City and
Orgrimmar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/138)
> Add missing Blasted Land Portal

- World/Updates/Rel21/Rel21_06_076_add_comment_column.sql
- Battleground_template now has a comment column.
- Updated Arena NPCs to corect bg_template ID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/139)
> Add Comment column to battleground_template

- World/Updates/Rel21/Rel21_06_077_HallowsEnd_updates.sql
- Added missing spawns for Candy Buckets as well as some missing
decorations.
- Horde Candy Bucket Quests are now linked to correct buckets.
- Added missing Apple bob objects.
**  There are still many missing decorations for this game event that
will need to be added at a later time as more reseach is needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/140)
> Hallows End Updates

- World/Updates/Rel21/Rel21_06_078_lower_npc_text_id.sql
Lower the current max ID value to allow proper future ID updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/141)
> Set current Max ID to a lower ID.

- World/Updates/Rel21/Rel21_06_080_draenei_mage_gossip.sql
Draenei mage trainers will now display the correct gossip for mages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/143)
> Update Draenei mage trainer gossip menu

- World/Updates/Rel21/Rel21_06_081_GO_Updates.sql
-Add missing game object
-New and existing old objects added to event spawns.
-Mesa Elevators now have corret rotations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/144)
> GO_Updates

- World/Updates/Rel21/Rel21_06_082_various_updates.sql
-- PX-238 Winter Wondervolt TRAP will activate and cast spell correctly.
-- Add Clockwork Rocket Bot to Winter Veil Gift.
-- Added Alliance loot to Bountiful Cookbook.
-- Added Snowball loot to Pocket Full of Snow.
-- Loot added to Crudely Wrapped Gift.
-- Loot added to Dertrok's Wand Case.
-- Curmudgeon's Payoff contains 5 gold.
-- Fix Z axis for NPCs, Kaymard Copperpinch, Penney Copperpinch, and
Great Father Winter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/145)
> Gobject, NPC and Item updates

- World/Updates/Rel21/Rel21_06_083_Princess_NPC_330_Update.sql
- Princess and her Porcine Entourage are not Slave/Master linked.
- Princess will now patrol around the field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/146)
> Princess NPC.330 Update

- World/Updates/Rel21/Rel21_07_003_Dragonblight_correction.sql
This will fix the Slave/Master issue from the previous Rel21_07_002
update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/148)
> Dragonblight update

- World/Updates/Rel21/Rel21_07_004_Shatter_point_update.sql
- Updates an Honor Hold Scoup run/walk db_script
- Remove Unused Honor Hold Scout Archery Target
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/149)
> Shatter_point_update

- World/Updates/Rel21/Rel21_07_005_Ramparts.sql
- Shattered Hand Warhound, Hellfire Watcher, Bonechewer Hungerer
Waypoints.  Ported most of the waypoint data from MangosOne, although
this data works, there is a lot of timing issues.
- Link Hellfire Sentry
- Reinforced Fel Iron Chest correctly positioned
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/150)
> Ramparts Update

- World/Updates/Rel21/Rel21_07_006_Princess_Stillpine_Script.sql
Princess Stillpine will thank the player rather than herself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/151)
> Update Princess Stillpine script

- World/Updates/Rel21/Rel21_07_008_Quest_10855_Fix.sql
Nether-Stalker Nauthis will now allow quest completion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/153)
> Quest. 10855 Flag update

- World/Updates/Rel21/Rel21_07_009_Inactive_Fel_Reaver.sql
The Inactive Fel Reavers have now been fully scripted when handing in
the quest 10850.  (Nether Gas In a Fel Fire Engine)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/154)
> Inactive Fel Reaver

- World/Updates/Rel21/Rel21_07_010_creatureAI_comment_update.sql
creature_ai_scripts ID 2022701 will now has the correct NPC in its
comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/155)
> creature AI scripts update

- World/Updates/Rel21/Rel21_07_011_gameobject_template_error_cleanup.sql
This update will finnish off the gameobject_template error cleanup for
Mangos 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/156)
> gameobject_template error cleanup

- World/Updates/Rel21/Rel21_07_035_Barrel_fix_Goldshire_HE.sql
Fixes the missing Water Barrel in Goldshire for the Hallow's End event
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/159)
> Water Barrel missing in Goldshire

- World/Updates/Rel21/Rel21_11_073_UBRS_models_add.sql
- World/Updates/Rel21/Rel21_11_074_UBRS_equip_models_add.sql
Added models creatures.
Added missing equipment for creatures.
Based on (sources):
https://github.com/cmangos/classic-db/commit/dcafa56c
https://github.com/cmangos/classic-db/commit/4b39c775
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/165)
> UBRS update part 1

- World/Updates/Rel22/Rel22_01_018_rethban_ore_root_samples.sql
* https://www.getmangos.eu/bug-tracker/cross-core/bugs/rethban-ore-quest-id-347-r1724/
* https://www.getmangos.eu/bug-tracker/cross-core/bugs/root-samples-quest-id-866-r1687/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/168)
> Add a database fix for Rethban Ore and Root Samples

- World/Updates/Rel22/Rel22_03_003_remove_subname_for_2694.sql
Removes a note used for Creature 2694's SubName.
Thanks @MadMaxMangos for pointing it out!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/173)
> Remove SubName for Creature 2694

- Character/Updates/Rel22/Rel22_05_001_Add_Quest_Tracker_Table.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/database/174)
> DB Update to Support Quest Tracking
